### ISSUE TITLE
Create crates.io release and move library to different workspace

### ISSUE THREAD

**Issue by qarmin** [Farmadupe/vid_dup_finder#1]
Hi,
Looks that your project allows to use duplicated videos, but currently I couldn't find any method how I could integrate it with my app Czkawka.

I suggest to move library to different workspaces and after that publish it in crates.io.

Currently also when I tried to compile app, I found that it require nightly Rust, which sadly prevents me from using it.

**Comment by Farmadupe** [comment]
Hello, sorry for the late reply!

As you have suggested, I have split up the codebase into a library and an application, and published both to crates.io
this repository now only contains the gui/cmdline application. 

I have also removed the need for a nightly compiler, and performed other refactorings. I have also written [documentation](https://docs.rs/vid_dup_finder_lib/0.1.0/vid_dup_finder_lib/) for the lirbary.

The source for the library is now located here: https://github.com/Farmadupe/vid_dup_finder_lib
