### ISSUE TITLE
Ability to adjust 30 second limit?

### ISSUE THREAD

**Issue by mishac** [Farmadupe/vid_dup_finder#4]
Can we have a way to change the 30 second limit?  I have a bunch of videos with an identical intro sequence and I'd like to adjust the limit to 2 minutes or more.   I understand that this increases the processing time, so keeping 30sec as default makes sense, but adding the ability to adjust this on a per-job basis would be very useful.

**Comment by Farmadupe** [comment]
All requested capabilities have now been added in the new "0.2.0" release of the library (also available on crates.io)
